brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import (
    TodoCreateView,
    TodoDeleteView,
    TodoItemUpdateView,
    TodoListView,
    TodoDetailView,
    TodoUpdateView,
    TodoItemCreateView,
)

urlpatterns = [
    path("", TodoListView.as_view(), name="list_todos"),
    path("<int:pk>/", TodoDetailView.as_view(), name="show_todolist"),
    path("create/", TodoCreateView.as_view(), name="create_todolist"),
    path("<int:pk>/edit/", TodoUpdateView.as_view(), name="update_todolist"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="delete_todolist"),
    path(
        "items/create/",
        TodoItemCreateView.as_view(),
        name="create_todoitem"
        ),
    path(
        "items/<int:pk>/edit/",
        TodoItemUpdateView.as_view(),
        name="update_todoitem"
    ),
]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    context_object_name = "todo_list"

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList", related_name="items", on_delete=models.CASCADE
    )

    def __str__(self):
        task = str(self.task)
        return task

todos/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.

from todos.models import TodoItem, TodoList


class TodoListView(ListView):
    model = TodoList
    template_name = "todos/list.html"


class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todos/detail.html"


class TodoCreateView(CreateView):
    model = TodoList
    template_name = "todos/create.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.id])


class TodoUpdateView(UpdateView):
    model = TodoList
    template_name = "todos/edit.html"
    fields = ["name"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.id])


class TodoDeleteView(DeleteView):
    model = TodoList
    template_name = "todos/delete.html"
    success_url = reverse_lazy("list_todos")


class TodoItemCreateView(CreateView):
    model = TodoItem
    template_name = "todo_items/create.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.list.id])


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    template_name = "todo_items/edit.html"
    fields = ["task", "due_date", "is_completed", "list"]

    def get_success_url(self):
        return reverse_lazy("show_todolist", args=[self.object.list.id])

todos/templates/todo_items/create.html
<!DOCTYPE html>
<html>
    <head>
        <title>Todo Lists</title>
    </head>
    <body>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Submit</button>
            </form>
        </div>
    </body>
</html>

todos/templates/todo_items/edit.html
<!DOCTYPE html>
<html>
    <head>
        <title>Todo List</title>
    </head>
    <body>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Update</button>
            </form>
        </div>
    </body>
</html>

todos/templates/todos/create.html
<!DOCTYPE html>
<html>
    <head>
        <title>Todo Lists</title>
    </head>
    <body>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Submit</button>
            </form>
        </div>
    </body>
</html>

todos/templates/todos/delete.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <div>
      <form method="post">
        {% csrf_token %}
        <h1>Are you sure?</h1>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <div>
        <h1>Reminders</h1>
        <p><a href="{% url 'update_todolist' todolist.id %}">Edit</a></p>
        <p><a href="{% url 'delete_todolist' todolist.id %}">Delete</a></p>
        <h2>Tasks</h2>
        <table>
          <thead>
            <tr>
              <th>Task</th>
              <th>Due date</th>
            </tr>
          </thead>
          <tbody>
            {% for item in todolist.items.all %}
                <tr>
                <td><a href="{% url 'update_todoitem' todolist.pk %}">{{ item.task }}</a></td>
                <td>{{ item.due_date }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </body>
</html>

todos/templates/todos/edit.html
<!DOCTYPE html>
<html>
    <head>
        <title>Todo List</title>
    </head>
    <body>
        <div>
            <h1>Update list</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Update</button>
            </form>
        </div>
    </body>
</html>

todos/templates/todos/list.html
<!DOCTYPE html>
<html>
  <head>
    <title>Todos Lists</title>
  </head>
  <body>
    <main>
      <div>
        <h1>My Lists</h1>
        <p><a href="{% url 'create_todolist' %}">Create a new list</a></p>
        <p><a href="{% url 'create_todoitem' %}">Create a new item</a></p>
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Number of items</th>
            </tr>
          </thead>
          <tbody>
            {% for list in todolist_list %}
            <tr>
              <td><a href="{% url 'show_todolist' list.pk %}">{{ list.name }}</a></td>
              <td>{{ list.items.all|length }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </body>
</html>